### ISSUE TITLE
ngdesktopfile.readFile: Callback function is never executed

### ISSUE THREAD

**Issue by monikawaser** [Servoy/ngdesktopfile#23]
ngdesktopfile.readFile(callback, path) is never executed.

Because it is executed asynchronously (we would need synchron), we made a while-Loop and wait for about 10 seconds. In this time the callback should execute. 
Explanation: We need the result immediatly and can't continue, until the callback is executed. 
Reason: We want move a Wordtemplate to the ngdesktop-Default Upload Location, so that the Server sees the Word-Template during the processing. The only way is, to get the Bytes with readFile und create the Word-Template in the Server-Temp-Path.

Further tests: 
I changed the wile-Loop and waited until 15 Minutes. In a other test I removed the waiting at all.
I noticed that the callback is never executed until I return to the UI. Thats too late.
For that reason I show a Message-Box after readFile; the program short returns in a "UI-Thread". As soon as the message box is displayed, the function is executed.
It means: As soon as the programmcode returns in a "UI-Thread" the callback is executed.

This can't be the solution. Message-Boxes are not a good idea during a processing. The callback must execute without return to UI.

Code see attached file.
![ngdesktopfile_readfile_problem](https://user-images.githubusercontent.com/60507046/215101606-53f3c380-234a-43dd-b61e-e8fe486c2402.jpg)

**Comment by jcompagner** [comment]
the whole point of a callback is exactly that
That it is called at some point in the future..
never do those kind of while loops

ngdesktop.readFile(callback)
should just be the last thing you do
and then you continue todo your stuff in the callback when you have the file..
so yes you can't do "return file.getAbsolutePath()" there
So currently you need to also make that "async" by returning a promise object or also using a callback in your own method 
which you store and then call with the absolute path

I do see that we do have readTXTFileSync (so with Sync in the name) that kind of does what you want, but then purely for txt files, we don't have a readFileSync i see. so potentially we could add that also.


But the current behavior of  callback is fully correct, as long as you block the event thread with a sleep or pure code, the callback will not be able to execute.. because you block the event thread.

**Comment by monikawaser** [comment]
Ok, I understand.
In this case we really need a new synchronous function: ngdesktop.readFileSync(callback)
I think, I do have to create an issue in the servoy dashboard (servoy.support.com)?

**Comment by mvid-servoy** [comment]
Sync function readFileSync() has been added to ngdesktopfile plugin and will be available with the next plugin release
