### ISSUE TITLE
cant open file from ngdesktop

### ISSUE THREAD

**Issue by r4inX** [Servoy/ngdesktopfile#3]
hey servoy team,
i have a issue with this plugin.
in developer-mode (straight from servoy) i can use:
`plugins.ngdesktopfile.openFile(_tmpPath.getAbsolutePath())`

on a tomcat server as a test for the client, i get the following error message form the ng-desktop client:

`servoy_thirdparty_svygrp17b5ecd02aa.js:133 Error (follows below) in parsing/processing this message: 52#{"services":[{"call":"openFile","args":["c:\\temp\\0_45680262438745667.png"],"name":"ngdesktopfile"}],"smsgid":7}
(anonymous) @ servoy_thirdparty_svygrp17b5ecd02aa.js:133
handleMessage @ websocket.js?svy_gid=17b5ecd02aa:374
websocket.onmessage @ websocket.js?svy_gid=17b5ecd02aa:696
(anonymous) @ reconnecting-websocket.js?svy_gid=17b5ecd02aa:179
ws.onmessage @ reconnecting-websocket.js?svy_gid=17b5ecd02aa:280
servoy_thirdparty_svygrp17b5ecd02aa.js:133 TypeError: shell.openPath is not a function
    at servoy_contributions_svygrp17b5ecd02aa.js:21810
    at waitForDefered (servoy_contributions_svygrp17b5ecd02aa.js:21379)
    at Object.openFile (servoy_contributions_svygrp17b5ecd02aa.js:21809)
    at handleMessage (websocket.js?svy_gid=17b5ecd02aa:296)
    at ReconnectingWebSocket.websocket.onmessage (websocket.js?svy_gid=17b5ecd02aa:696)
    at HTMLDivElement.<anonymous> (reconnecting-websocket.js?svy_gid=17b5ecd02aa:179)
    at WebSocket.ws.onmessage (reconnecting-websocket.js?svy_gid=17b5ecd02aa:280)`

things i tried:

change the temppath from the tomcat/tmp path to c:\temp\

from what i understand: electron cant find the function: shell.openpath()
i know that it was a issue, so electron changed shell.openitem() to shell.openpath()
the weird thing is that in delevoper is it working fine.
![ng_desktop_file_error_1](https://user-images.githubusercontent.com/28804733/130089541-21a2ff56-c8d0-4d4d-a590-b709f847b0a7.PNG)
![ng_desktop_file_error_2](https://user-images.githubusercontent.com/28804733/130089546-53552c5a-d958-4eb4-b5b4-ee7015a6e8c6.PNG)

maybe you guys have a idea, is it maybe a setting that is not documented anywhere?

greetings

**Comment by seanthomasdevlin** [comment]
Hi Vik,

An issue has been created in our support system:
https://support.servoy.com/browse/SVYX-305

You can subscribe yourself as "watcher" for updates. This github issue will also be updated when there is a resolution.

Best,
Sean

**Comment by jcompagner** [comment]
You can't open a file from the server...
you first need to save that file to a temp location on the client (ngdesktopfile.writeFile)
then the file you have written at the client you can open..

I guess what we must do here is make sure the doc of openFile makes this really clear that you need to use a local file (local on the client not the server)

we can't also just write it for you because plugins.ngdesktopfile.openFile(path) we can't know that you really mean a path on the server (it can exist in both area's we don't know)

**Comment by jcompagner** [comment]
some comments i also added to the other case: (because is not a function is really weird error)

to be sure, what is _tmpPath ? is that really a path on the client where ngdesktop application is running?

so you did first use writeFile(_tmpPath) ?

the weird thing it says it is not a function but openPath should there already be for quite some time (and it still is)

electron 11 (the current released ngdesktop) https://github.com/electron/electron/blob/v11.0.0/docs/api/shell.md#shellopenpathpath

has openPath 

 

the same with 13 (where the next version will be build on https://www.electronjs.org/docs/api/shell#shellopenpathpath

**Comment by r4inX** [comment]
Hey, yes we do create the file on the client pc where the ngdesktop client is running.
The files are beeing created, I can open the folder and see them in windows.
Yes we do write the file first (_tmpPath) for example c:\tmp\0001.bmp

The files are there and okay. Standard windows apps for opening those files are set (acrobat, paint, etc)

I know that we can't open files directly from the server, that's why we create them locally on the client pc.

Thanks for the help

**Comment by r4inX** [comment]
And yes, shell.openPath() is in your code, I checked it. It was added a while ago.
